version: "3.9"

services:
  control:
    container_name: rov_control
    build: .
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./control_service:/app
    environment:
      - MAVLINK_URL=udpin:0.0.0.0:14550
      - UI_WS_PORT=8765
